# Netlify configuration for static frontend deployment
# Note: This is for frontend-only deployment. Backend must be deployed separately.

[build]
  base = "frontend/"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to your backend
# Replace YOUR_BACKEND_URL with your actual backend URL (e.g., from Render)
[[redirects]]
  from = "/api/*"
  to = "YOUR_BACKEND_URL/api/:splat"
  status = 200
  force = true

# SPA routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"