services:
  # Web service for stateless deployment (no database)
  - type: web
    name: prompteval-lite
    runtime: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Build frontend
      cd frontend
      npm install
      npm run build
      # Copy built files to static directory
      cd ..
      mkdir -p static
      cp -r frontend/dist/* static/
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      # Required - You must set this in Render dashboard
      - key: GOOGLE_API_KEY
        sync: false
      
      # Disable database for stateless deployment
      - key: ENABLE_DATABASE
        value: false
      
      # Model Configuration
      - key: DEFAULT_MODEL
        value: gemini-2.5-flash
      - key: EVALUATOR_MODEL
        value: gemini-2.5-flash
      
      # Application Settings
      - key: LOG_LEVEL
        value: INFO
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 60
      - key: MAX_SYNTHETIC_CASES
        value: 10
      - key: REQUEST_TIMEOUT
        value: 60
      
      # Required placeholders for stateless mode
      - key: JWT_SECRET_KEY
        value: stateless-mode-placeholder-key-not-used
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_HOURS
        value: 24
      - key: ENCRYPTION_KEY
        value: gAAAAABhZ0123456789012345678901234567890-_aaaaaaaaa